apiVersion: apps/v1
kind: Deployment
metadata:
  name: testkube-example-service
  labels:
    app: testkube-example-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testkube-example-service
  template:
    metadata:
      labels:
        app: testkube-example-service
    spec:
      containers:
        - name: testkube-example-service
          image: kubeshop/testkube-example-service:latest
          ports:
            - containerPort: 8881
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 64Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: testkube-example-service
spec:
  selector:
    app: testkube-example-service
  ports:
    - protocol: TCP
      port: 8881
      targetPort: 8881
