before:
  hooks:
    - go mod tidy
dist: windows
builds:
  - main: ./cmd/kubectl-testkube
    binary: kubectl-testkube
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -X github.com/kubeshop/testkube/pkg/analytics.TestkubeMeasurementID=123
      - -X github.com/kubeshop/testkube/pkg/analytics.TestkubeMeasurementSecret=134
archives:
  - format: binary
