before:
  hooks:
    - go mod tidy
dist: darwin
builds:
  - main: ./cmd/kubectl-testkube
    binary: kubectl-testkube
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -X github.com/kubeshop/testkube/pkg/analytics.TestkubeMeasurementID=123
      - -X github.com/kubeshop/testkube/pkg/analytics.TestkubeMeasurementSecret=123
archives:
  - format: binary
