site_name: Kubtest
site_description: 'Your Kubernetes Testing Friend'
site_author: 'Kubeshop kubtest Team'
docs_dir: docs/
repo_name: 'kubeshop/kubtest'
repo_url: 'https://github.com/kubeshop/kubtest'
edit_uri: blob/main/docs/

theme:
  name: material
  locale: en
  features:
    - navigation.expand

nav:
  - Welcome: index.md
  - Installation: installing.md
  - Getting Started: getting-started.md
  - Dashboard: dashboard.md
  - Managing test scripts:
      - Creating: scripts-creating.md
      - Running: scripts-running.md
      - Getting results: scripts-getting-results.md
  - Executors:
      - Postman Collections: executor-postman.md
      - Cypress Tests: executor-cypress.md
      - Curl Commands: executor-curl.md
      - Creating your own: executor-custom.md
  - CLI Reference:
      - Overview:  cli/kubtest.md
      - Install Cmd: cli/kubtest_install.md
      - Scripts Cmd: cli/kubtest_scripts.md
      - Completion Cmd: cli/kubtest_completion.md
      - Version Cmd: cli/kubtest_version.md
  - Metrics: metrics.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Development: development.md
  - OpenAPI definition: openapi.md

extra:
  analytics:
    provider: google
    property: UA-204665550-6

  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - render_swagger

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

copyright: Copyright &copy; 2021 <a href="https://kubeshop.io">Kubeshop</a>

