name: Release kubectl-testkube

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+"

jobs:

  # release_creation:
  #   name: Prepares Release on GitHub
  #   runs-on: ubuntu-latest
  #   outputs:
  #     id: ${{ steps.main_step.outputs.id }}
  #   steps:
  #     - name: Create Release
  #       id: main_step
  #       uses: actions/create-release@latest
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: testkube CLI ${{ github.ref }}
  #         body: |
  #           Changes in this Release
  #           - Releasing new version of the testkube CLI for Kubectl.
  #         draft: false
  #         prerelease: false

  release:
    name: Create and upload release-artifacts
    # needs: [release_creation]
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist -f .goreleaser-dev.yml
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          ANALYTICS_TRACKING_ID: "${{secrets.TESTKUBE_ANALYTICS_TRACKING_ID}}"
          ANALYTICS_API_KEY: "${{secrets.TESTKUBE_ANALYTICS_API_SECRET}}"
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      -
        name: Store Intermediate Artifacts
        uses: actions/upload-artifact@master
        with:
          name: bin-artifacts
          path: dist
          retention-days: 1 
      # -
      #   name: Bump formulae
      #   uses: Homebrew/actions/bump-formulae@master
      #   with:
      #     # Custom GitHub access token with only the 'public_repo' scope enabled
      #     token: ${{ secrets.CI_BOT_TOKEN }}
      #     # Bump only these formulae if outdated
      #     formulae: testkube

  build-and-publish-windows:
    needs: release
    runs-on: windows-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Intermediate Artifacts
        uses: actions/download-artifact@master
        with:
          name: bin-artifacts
          path: dist

      - name: Get MSFT Cert
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'kubeshop_msft.p12'
          fileDir: './temp/'
          encodedString: ${{ secrets.CERT_MSFT_KUBESHOP_P12_B64 }}
      
      - name: Create MSI
        run: |
          Copy-Item 'dist\testkube_windows_386\kubectl-testkube.exe' '.\kubectl-testkube.exe'
          Copy-Item 'build\installer\windows\testkube.wxs' '.\testkube.wxs'
          & "$env:WIX\bin\candle.exe" *.wxs
          & "$env:WIX\bin\light.exe" *.wixobj
          dir
          dir "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool"

           
