name: Code build and checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Unit test
      run: go test -v ./...

    # Runs a single command using the runners shell
    - name: openapi-check
      uses: vaibhav-jain/spectral-action/@v2.6
      with:
        file_path: api/testkube.yaml